spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.211:8848
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint:
  application:
    name: mall-third


server:
  port: 8090